default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  host: localhost
  database: instagram_development
  port: 5433
  username: postgres
  password: namakualam

test:
  <<: *default
  host: localhost
  database: instagram_test
  port: 5433
  username: postgres
  password: namakualam


production:
  <<: *default
  host: localhost
  database: instagram_production
  port: 5433
  username: postgres
  password: namakualam
